[tool.black]
line-length = 88
target-version = ["py39", "py310", "py311"]

[tool.isort]
src_paths = ["mha2sha"]
extra_standard_library = ["typing_extensions"]
skip_gitignore = true
atomic = true
profile = "black"
indent = 4
line_length = 88
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = true


[tool.ruff]
target-version = "py38"
line-length = 120
